name: EAS Update
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to your Expo account"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Show debug info
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in directory:"
          ls -la
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "Expo CLI version: $(npx expo --version)"
          echo "EAS CLI version: $(npx eas-cli --version)"

      - name: Verify EAS configuration
        run: |
          echo "Content of app.json:"
          cat app.json
          echo "Content of eas.json:"
          cat eas.json

      - name: Publish update
        run: |
          # Aumentar limite de memória para Node.js
          export NODE_OPTIONS=--max_old_space_size=8192
          # Instalar explicitamente o EAS CLI
          npm install -g eas-cli
          # Executar o update com o caminho completo
          npx eas-cli update --auto --non-interactive --message "Automatic update from GitHub Actions $(date +%Y-%m-%d-%H:%M)" 